import {
  PlayerGroundMovementConfig,
  PlayerJumpConfig,
} from "../../types/player-types/player-physics-types";

export const PLAYER_JUMP_CONFIG: PlayerJumpConfig = {
  GRAVITY: 1000,
  JUMP_VELOCITY: -600,
  FORWARD_JUMP_VELOCITY_X: 400,
  FORWARD_JUMP_VELOCITY_Y: -600,
  RUN_JUMP_VELOCITY_X: 500,
  RUN_JUMP_VELOCITY_Y: -600,
  HEAVY_LANDING_THRESHOLD: 567,
  MAX_HEAVY_LANDING_THRESHOLD: 900,
  HEAVY_LANDING_IMPACT_VELOCITY: 400,
};

export const PLAYER_GROUND_MOVEMENT_CONFIG: PlayerGroundMovementConfig = {
  MAX_SPEED: 500,
  MAX_WALK_SPEED: 250,
  ROLLING_SPEED: 200,
  RUN_ACCELERATION: 1500,
  WALK_ACCELERATION: 750,
  RUN_STOP_DECELERATION: 2000,
  WALK_STOP_DECELERATION: 1000,
  ROLLING_DECELERATION: 1000,
};
